services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=diplomdb'
      - 'POSTGRES_PASSWORD=diploma333'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'
